### PR TITLE
Fix: aggregation pipeline to call $search first

### LINKED ISSUE #200: Search in the Boardings page fails with an internal error
**Describe the bug**

**To Reproduce**
1. Go to the **Boardings page**
2. Click on search for **Mia**
3. See error

**Expected behavior**
A list of boardings should appear

**Screenshots**
Here is a screenshot of the error
image

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Browser Version: 87

**Additional context**
I tested it with our sandbox app: https://internaltesting-burqd.mongodbstitch.com/

### PR DESCRIPTION
**Pull request by sebawita**
the aggregate pipeline was broken, as `aggregateTerms` - which contains `$search` - was placed after `agencyAggregate`.
Which caused the following error:
```
"(Location40602) $_internalSearchMongotRemote is only valid as the first stage in a pipeline.
uncaught promise rejection: (Location40602) $_internalSearchMongotRemote is only valid as the first stage in a pipeline."
```

Swapping them around placed the `$search` first, and fixed the issue

## Related Issue

Fixes #200

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 
I have tested the changes in my clone of the environment, which works as expected.

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

File: WildAidDemo/functions/searchFacetByBoardings/source.js [hunk 1]
```diff
@@ -178,22 +175,25 @@ exports = function(limit, offset, query, filter, agenciesToShareData){
...
+      agencyAggregate, {
         '$skip': offset
       }, {
         '$limit': limit
       }
     ]).toArray();
 
-    var highlighted = boardingsCollection.aggregate([agencyAggregate,
-      aggregateTerms, {
+    const highlighted = boardingsCollection.aggregate([
```
Comment (npentrel) [inline WildAidDemo/functions/searchFacetByBoardings/source.js:194]: does this need to be a `const`? @sebawita

**Comment by npentrel** [comment]
This looks good @sebawita. Let me know about the `const` and then I can merge this :)

File: WildAidDemo/functions/searchFacetByBoardings/source.js (hunk 1 above)
Comment (sebawita) [reply WildAidDemo/functions/searchFacetByBoardings/source.js:194]: This would also work with `var`, however since `highlighted` won't be reassigned anywhere after this line, it is better to keep it as a const.
This way we can make sure that nobody introduces additional changes to this aggregation.
